use crate::core_types::Position;
use super::types::{MonsterKind, SpecialHit};

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Monster {
    pub kind: MonsterKind,
    pub position: Position,
    pub hit_points: i16,
    /// Damage string in `"NdD"` or `"NdD/NdD"` format, matching original `mon_tab`.
    pub damage_string: &'static str,
    /// Hit-chance percentage (0-100), matching original `m_hit_chance` in `mon_tab`.
    pub hit_chance: i16,
    /// Experience points awarded to the player on kill, matching original `kill_exp`.
    pub kill_exp: i32,
    pub special_hit: Option<SpecialHit>,
    /// Cumulative damage for STATIONARY monsters (VenusFlytrap): starts at 0, +1 each attack.
    pub stationary_damage: i16,
    /// True while the monster is still pursuing a floor-gold pile (SEEKS_GOLD flag in original).
    /// Cleared when the monster steps onto a gold tile or the player attacks it.
    pub seeks_gold: bool,
}

impl Monster {
    pub const fn new(kind: MonsterKind, position: Position) -> Self {
        match kind {
            MonsterKind::Aquator => Self {
                kind,
                position,
                hit_points: 25,
                damage_string: "0d0",
                hit_chance: 100,
                kill_exp: 20,
                special_hit: Some(SpecialHit::Rusts),
                stationary_damage: 0,
                seeks_gold: false,
            },
            MonsterKind::Bat => Self {
                kind,
                position,
                hit_points: 10,
                damage_string: "1d3",
                hit_chance: 60,
                kill_exp: 2,
                special_hit: None,
                stationary_damage: 0,
                seeks_gold: false,
            },
            MonsterKind::Centaur => Self {
                kind,
                position,
                hit_points: 32,
                damage_string: "3d3/2d5",
                hit_chance: 85,
                kill_exp: 15,
                special_hit: None,
                stationary_damage: 0,
                seeks_gold: false,
            },
            MonsterKind::Dragon => Self {
                kind,
                position,
                hit_points: 145,
                damage_string: "4d6/4d9",
                hit_chance: 100,
                kill_exp: 5000,
                special_hit: Some(SpecialHit::Flames),
                stationary_damage: 0,
                seeks_gold: false,
            },
            MonsterKind::Emu => Self {
                kind,
                position,
                hit_points: 11,
                damage_string: "1d3",
                hit_chance: 65,
                kill_exp: 2,
                special_hit: None,
                stationary_damage: 0,
                seeks_gold: false,
            },
            MonsterKind::VenusFlytrap => Self {
                kind,
                position,
                hit_points: 73,
                damage_string: "0d0",
                hit_chance: 80,
                kill_exp: 91,
                special_hit: Some(SpecialHit::Hold),
                stationary_damage: 0,
                seeks_gold: false,
            },
            MonsterKind::Griffin => Self {
                kind,
                position,
                hit_points: 115,
                damage_string: "5d5/5d5",
                hit_chance: 85,
                kill_exp: 2000,
                special_hit: None,
                stationary_damage: 0,
                seeks_gold: false,
            },
            MonsterKind::Hobgoblin => Self {
                kind,
                position,
                hit_points: 15,
                damage_string: "1d3/1d2",
                hit_chance: 67,
                kill_exp: 3,
                special_hit: None,
                stationary_damage: 0,
                seeks_gold: false,
            },
            MonsterKind::IceMonster => Self {
                kind,
                position,
                hit_points: 15,
                damage_string: "0d0",
                hit_chance: 68,
                kill_exp: 5,
                special_hit: Some(SpecialHit::Freeze),
                stationary_damage: 0,
                seeks_gold: false,
            },
            MonsterKind::Jabberwock => Self {
                kind,
                position,
                hit_points: 132,
                damage_string: "3d10/4d5",
                hit_chance: 100,
                kill_exp: 3000,
                special_hit: None,
                stationary_damage: 0,
                seeks_gold: false,
            },
            MonsterKind::Kestrel => Self {
                kind,
                position,
                hit_points: 10,
                damage_string: "1d4",
                hit_chance: 60,
                kill_exp: 2,
                special_hit: None,
                stationary_damage: 0,
                seeks_gold: false,
            },
            MonsterKind::Leprechaun => Self {
                kind,
                position,
                hit_points: 25,
                damage_string: "0d0",
                hit_chance: 75,
                kill_exp: 21,
                special_hit: Some(SpecialHit::StealsGold),
                stationary_damage: 0,
                seeks_gold: false,
            },
            MonsterKind::Medusa => Self {
                kind,
                position,
                hit_points: 97,
                damage_string: "4d4/3d7",
                hit_chance: 85,
                kill_exp: 250,
                special_hit: Some(SpecialHit::Confuse),
                stationary_damage: 0,
                seeks_gold: false,
            },
            MonsterKind::Nymph => Self {
                kind,
                position,
                hit_points: 25,
                damage_string: "0d0",
                hit_chance: 75,
                kill_exp: 39,
                special_hit: Some(SpecialHit::StealsItem),
                stationary_damage: 0,
                seeks_gold: false,
            },
            MonsterKind::Orc => Self {
                kind,
                position,
                hit_points: 25,
                damage_string: "1d6",
                hit_chance: 70,
                kill_exp: 5,
                special_hit: None,
                stationary_damage: 0,
                seeks_gold: true,
            },
            MonsterKind::Phantom => Self {
                kind,
                position,
                hit_points: 76,
                damage_string: "5d4",
                hit_chance: 80,
                kill_exp: 120,
                special_hit: None,
                stationary_damage: 0,
                seeks_gold: false,
            },
            MonsterKind::Quagga => Self {
                kind,
                position,
                hit_points: 30,
                damage_string: "3d5",
                hit_chance: 78,
                kill_exp: 20,
                special_hit: None,
                stationary_damage: 0,
                seeks_gold: false,
            },
            MonsterKind::Rattlesnake => Self {
                kind,
                position,
                hit_points: 19,
                damage_string: "2d5",
                hit_chance: 70,
                kill_exp: 10,
                special_hit: Some(SpecialHit::Sting),
                stationary_damage: 0,
                seeks_gold: false,
            },
            MonsterKind::Snake => Self {
                kind,
                position,
                hit_points: 8,
                damage_string: "1d3",
                hit_chance: 50,
                kill_exp: 2,
                special_hit: None,
                stationary_damage: 0,
                seeks_gold: false,
            },
            MonsterKind::Troll => Self {
                kind,
                position,
                hit_points: 75,
                damage_string: "4d6/1d4",
                hit_chance: 75,
                kill_exp: 125,
                special_hit: None,
                stationary_damage: 0,
                seeks_gold: false,
            },
            MonsterKind::BlackUnicorn => Self {
                kind,
                position,
                hit_points: 90,
                damage_string: "4d10",
                hit_chance: 85,
                kill_exp: 200,
                special_hit: None,
                stationary_damage: 0,
                seeks_gold: false,
            },
            MonsterKind::Vampire => Self {
                kind,
                position,
                hit_points: 55,
                damage_string: "1d14/1d4",
                hit_chance: 85,
                kill_exp: 350,
                special_hit: Some(SpecialHit::DrainsLife),
                stationary_damage: 0,
                seeks_gold: false,
            },
            MonsterKind::Wraith => Self {
                kind,
                position,
                hit_points: 45,
                damage_string: "2d8",
                hit_chance: 75,
                kill_exp: 55,
                special_hit: Some(SpecialHit::DropsLevel),
                stationary_damage: 0,
                seeks_gold: false,
            },
            MonsterKind::Xeroc => Self {
                kind,
                position,
                hit_points: 42,
                damage_string: "4d6",
                hit_chance: 75,
                kill_exp: 110,
                special_hit: None,
                stationary_damage: 0,
                seeks_gold: false,
            },
            MonsterKind::Yeti => Self {
                kind,
                position,
                hit_points: 35,
                damage_string: "3d6",
                hit_chance: 80,
                kill_exp: 50,
                special_hit: None,
                stationary_damage: 0,
                seeks_gold: false,
            },
            MonsterKind::Zombie => Self {
                kind,
                position,
                hit_points: 21,
                damage_string: "1d7",
                hit_chance: 69,
                kill_exp: 8,
                special_hit: None,
                stationary_damage: 0,
                seeks_gold: false,
            },
        }
    }

    pub const fn display_char(&self) -> char {
        self.kind.display_char()
    }
}

impl MonsterKind {
    /// Returns the (first_level, last_level) range from the original mon_tab.
    pub const fn level_range(self) -> (i16, i16) {
        match self {
            MonsterKind::Aquator      => (9,  18),
            MonsterKind::Bat          => (1,  8),
            MonsterKind::Centaur      => (7,  16),
            MonsterKind::Dragon       => (21, 126),
            MonsterKind::Emu          => (1,  7),
            MonsterKind::VenusFlytrap => (12, 126),
            MonsterKind::Griffin      => (20, 126),
            MonsterKind::Hobgoblin    => (1,  10),
            MonsterKind::IceMonster   => (2,  11),
            MonsterKind::Jabberwock   => (21, 126),
            MonsterKind::Kestrel      => (1,  6),
            MonsterKind::Leprechaun   => (6,  16),
            MonsterKind::Medusa       => (18, 126),
            MonsterKind::Nymph        => (10, 19),
            MonsterKind::Orc          => (4,  13),
            MonsterKind::Phantom      => (15, 24),
            MonsterKind::Quagga       => (8,  17),
            MonsterKind::Rattlesnake  => (3,  12),
            MonsterKind::Snake        => (1,  9),
            MonsterKind::Troll        => (13, 22),
            MonsterKind::BlackUnicorn => (17, 26),
            MonsterKind::Vampire      => (19, 126),
            MonsterKind::Wraith       => (14, 23),
            MonsterKind::Xeroc        => (16, 25),
            MonsterKind::Yeti         => (11, 20),
            MonsterKind::Zombie       => (5,  14),
        }
    }

    pub const fn display_char(self) -> char {
        match self {
            MonsterKind::Aquator => 'A',
            MonsterKind::Bat => 'B',
            MonsterKind::Centaur => 'C',
            MonsterKind::Dragon => 'D',
            MonsterKind::Emu => 'E',
            MonsterKind::VenusFlytrap => 'F',
            MonsterKind::Griffin => 'G',
            MonsterKind::Hobgoblin => 'H',
            MonsterKind::IceMonster => 'I',
            MonsterKind::Jabberwock => 'J',
            MonsterKind::Kestrel => 'K',
            MonsterKind::Leprechaun => 'L',
            MonsterKind::Medusa => 'M',
            MonsterKind::Nymph => 'N',
            MonsterKind::Orc => 'O',
            MonsterKind::Phantom => 'P',
            MonsterKind::Quagga => 'Q',
            MonsterKind::Rattlesnake => 'R',
            MonsterKind::Snake => 'S',
            MonsterKind::Troll => 'T',
            MonsterKind::BlackUnicorn => 'U',
            MonsterKind::Vampire => 'V',
            MonsterKind::Wraith => 'W',
            MonsterKind::Xeroc => 'X',
            MonsterKind::Yeti => 'Y',
            MonsterKind::Zombie => 'Z',
        }
    }

    /// Percentage chance (0–100) that killing this monster drops an item,
    /// matching `drop_percent` in the original `mon_tab` (monster.c).
    pub const fn drop_percent(self) -> i32 {
        match self {
            MonsterKind::Aquator      =>   0,
            MonsterKind::Bat          =>  10,
            MonsterKind::Centaur      =>  15,
            MonsterKind::Dragon       => 100,
            MonsterKind::Emu          =>  10,
            MonsterKind::VenusFlytrap =>   0,
            MonsterKind::Griffin      =>  20,
            MonsterKind::Hobgoblin    =>  10,
            MonsterKind::IceMonster   =>   0,
            MonsterKind::Jabberwock   =>  70,
            MonsterKind::Kestrel      =>  10,
            MonsterKind::Leprechaun   =>   0,
            MonsterKind::Medusa       =>  40,
            MonsterKind::Nymph        => 100,
            MonsterKind::Orc          =>  15,
            MonsterKind::Phantom      =>  20,
            MonsterKind::Quagga       =>  15,
            MonsterKind::Rattlesnake  =>  10,
            MonsterKind::Snake        =>   0,
            MonsterKind::Troll        =>  35,
            MonsterKind::BlackUnicorn =>  60,
            MonsterKind::Vampire      =>  20,
            MonsterKind::Wraith       =>   0,
            MonsterKind::Xeroc        =>  30,
            MonsterKind::Yeti         =>  30,
            MonsterKind::Zombie       =>   0,
        }
    }
}

